### ISSUE TITLE
Good Job! Does it work ?

### ISSUE THREAD

**Issue by gunish** [mooyoul/angulartics-facebook-pixel#1]
Good Job on creating this! Is this ready to use / does it work right now ?

**Comment by mooyoul** [comment]
Yes, It is ready to use, tested pageview suceessfully counted on Facebook Advertisement console (dashboard), and **production-ready**.
We are already using this package on production service ([Visit www.lawtalk.co.kr](https://www.lawtalk.co.kr) with Facebook Pixel Helper which available on Chrome Extension)

**Comment by mooyoul** [comment]
but it is doesn't registered to package repos like `bower`, `npm`, and not yet documented.

Due to [angulartics plugin contribution rules](https://github.com/luisfarzati/angulartics/wiki/Plugin-contribution-rules), this package doesn't satisfy some rules.

So i won't release this package to package repo until these contribution rules was resolved.
but, I am working on this. and will release package ASAP.

## If you want to use this package before public release, Please refer below instruction.

### (Optional) Install this plugin from git using bower

``` bash
bower install --save mooyoul/angulartics-facebook-pixel
```

### 1. Insert facebook pixel tracking script in `<head>` tag

``` html
<head>
    ...
    <!-- Facebook Pixel Code -->
    <script>
      !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
              document,'script','//connect.facebook.net/en_US/fbevents.js');
      fbq('init', YOUR_PIXEL_ID);
    </script>
    <noscript>
      <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=YOUR_PIXEL_ID&ev=PageView&noscript=1">
    </noscript>
    <!-- End Facebook Pixel Code -->
    ...
```

### 2. Insert `angulartics-facebook-pixel` plugin with `angulartics`

``` html
...
<script src="/bower_components/angulartics/src/angulartics.js"></script>
<script src="/bower_components/angulartics-facebook-pixel/dist/angulartics-facebook-pixel.min.js"></script>
...
```

### 3. Add _angulartics.facebook.pixel_ as a dependency for your app

``` javascript
angular.module('myApp', [
  'angulartics', 
  'angulartics.facebook.pixel'
]);
```

### 4. Enjoy!

**Comment by gunish** [comment]
:+1:

**Comment by mooyoul** [comment]
@gunish Yay! I just published this package to NPM, and Bower.
You can install this plugin using `npm install angulartics-facebook-pixel`, or `bower install angulartics-facebook-pixel` now.

See details on [README](https://github.com/mooyoul/angulartics-facebook-pixel#angulartics-facebook-pixel).

Let me know plugin working properly, and give me a star if you satisfied this plugin :stars:
